---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: trace
    waitFor: ['-']
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - trace
      - --trigger-http
      - --runtime
      - nodejs12
      - --memory
      - 1GB
      - --source
      - orig/tracer
      - --env-vars-file
      - orig/env-vars.yaml
      - --entry-point
      - trace
      - --gen2
      - --region
      - ${_REGION}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: analyze
    waitFor: ['-']
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - analyze
      - --trigger-resource
      - ${_METRICS_BUCKET}
      - --trigger-event
      - google.storage.object.finalize
      - --runtime
      - python38
      - --source
      - orig/analyzer
      - --env-vars-file
      - orig/env-vars.yaml
      - --gen2
      - --region
      - ${_REGION}

substitutions:
  _METRICS_BUCKET: metrics-automatic-winner
  _REGION: asia-northeast1
