---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: trace
    waitFor: ['-']
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - trace
      - --trigger-http
      - --runtime
      - nodejs12
      - --memory
      - 1GB
      - --source
      - orig/tracer
      - --env-vars-file
      - orig/env-vars.yaml
      - --entry-point
      - trace
      - --gen2
      - --region
      - ${_REGION}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: analyze
    waitFor: ['-']
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - analyze
      - --trigger-resource
      - ${_METRICS_BUCKET}
      - --trigger-event
      - google.storage.object.finalize
      - --runtime
      - python38
      - --source
      - orig/analyzer
      - --entry-point
      - analyze
      - --env-vars-file
      - orig/env-vars.yaml
      - --gen2
      - --region
      - ${_REGION}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: alert
    waitFor: ['-']
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - analyze
      - --env-vars-file=orig/env-vars.yaml
      - --entry-point=generate_alert
      - --runtime=python38
      - --region=${_REGION}
      - --source=orig/alerter
      - --trigger-event=providers/cloud.firestore/eventTypes/document.create
      - --trigger-resource="projects/${PROJECT_ID}/databases/(default)/documents/page-metrics/{any}"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: scheduler
    waitFor: ['trace']
    script: |
      #!/bin/sh
      apt-get -y install jq
      gcloud functions describe trace --gen2 --region asia-northeast1

substitutions:
  _METRICS_BUCKET: metrics-automatic-winner
  _REGION: asia-northeast1
